## Algorithms for One-hot encoding

In [0]:
# Import required libraries
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [0]:
# Read HBB and HEXA file
df5 = pd.read_excel("onehot.xlsx")

In [0]:
df5 = df5.drop(['Unnamed: 0'], axis=1)

In [0]:
# Features
X = df5.drop('Mean of correct edit', axis=1)

In [0]:
# Target variable
y = df5['Mean of correct edit']

In [0]:
# Splitting the dataset into the Training and Test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

## Multiple Linear Regression Model

In [0]:
# Import Multiple Linear Regression Model
from sklearn.linear_model import LinearRegression

In [33]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
# Use the regressor's predict method on the test data
pred= regressor.predict(X)

In [0]:
# Place predictions in the dataframe
df5['Predictions'] = pd.DataFrame(data=pred)

In [0]:
results = df5[['Mean of correct edit', 'Predictions']]

In [37]:
# Print the actual values and the model's predictions
results

    Mean of correct edit  Predictions
0              40.982414     2.142732
1              32.843033    34.178042
2              36.210669    36.210669
3              46.204905    47.016416
4              42.342045    41.007035
5              44.501013    45.468979
6              38.488102    61.930128
7              29.187135    27.852126
8              29.959730    29.884752
9              40.690499    40.690499
10             33.346109    34.681119
11             39.143062    39.143062
12             31.461293    14.120227
13              0.232247    -5.906912
14              0.243254    -2.892742
15              0.980358    -1.354576
16              3.285856     5.023659
17              4.693972    12.761767
18              7.288269    10.453322
19              7.889493    -3.638793
20              0.343363     0.343363
21              0.221537     3.357534
22              2.560767     4.895700
23             13.011737    11.273934
24             19.012042    19.012042
25             19.868651    16.703598
26             22.122870     2.611483
27             22.895820    22.895820
28             15.632697    15.632697
29             12.021063    12.021063
30              9.072358     4.827724
31              7.162188     8.987863
32             11.391022    10.133420
33             11.071509     0.134108
34             32.697945    40.550309
35             24.046569    25.578284
36             32.673327    65.518638
37             27.980605    27.980605
38             31.558509    29.458721
39             27.867751    23.221556
40             14.748934    14.748934
41             13.799727    14.367801
42             25.213954    26.471555
43             24.322523    24.322523
44             24.812133    33.620305
45             26.585110    29.405630
46              9.320976    11.450154
47             16.740829    16.925573
48             17.692417    16.667301
49             16.343508    18.443296
50             19.979771    57.659877
51             18.711186    16.582008
52             22.242170    22.057426
53             22.305753    21.799154
54             14.134634    23.575149
55              0.145917    -0.422156

In [38]:
import sklearn.metrics as metrics

# Calculate MAE, MSE, RMSE
print(metrics.mean_absolute_error(df5['Mean of correct edit'],pred))
print(metrics.mean_squared_error(df5['Mean of correct edit'], pred))
print(np.sqrt(metrics.mean_squared_error(df5['Mean of correct edit'], pred)))

5.16883133499603
106.4896521570972
10.319382353469475

# Support Vector Regression

In [0]:
from sklearn.svm import SVR

In [0]:
# Use the regressor's predict method on the test data
SupportVectorRegModel = SVR()

In [48]:
SupportVectorRegModel.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
# Use the regressor's predict method on the test data
pred= SupportVectorRegModel.predict(X)

In [0]:
# Place predictions in the dataframe
df5['Predictions2'] = pd.DataFrame(data=pred)

In [0]:
results = df5[['Mean of correct edit', 'Predictions']]

In [54]:
# Print the actual values and the model's predictions
results

    Mean of correct edit  Predictions
0              40.982414     2.142732
1              32.843033    34.178042
2              36.210669    36.210669
3              46.204905    47.016416
4              42.342045    41.007035
5              44.501013    45.468979
6              38.488102    61.930128
7              29.187135    27.852126
8              29.959730    29.884752
9              40.690499    40.690499
10             33.346109    34.681119
11             39.143062    39.143062
12             31.461293    14.120227
13              0.232247    -5.906912
14              0.243254    -2.892742
15              0.980358    -1.354576
16              3.285856     5.023659
17              4.693972    12.761767
18              7.288269    10.453322
19              7.889493    -3.638793
20              0.343363     0.343363
21              0.221537     3.357534
22              2.560767     4.895700
23             13.011737    11.273934
24             19.012042    19.012042
25             19.868651    16.703598
26             22.122870     2.611483
27             22.895820    22.895820
28             15.632697    15.632697
29             12.021063    12.021063
30              9.072358     4.827724
31              7.162188     8.987863
32             11.391022    10.133420
33             11.071509     0.134108
34             32.697945    40.550309
35             24.046569    25.578284
36             32.673327    65.518638
37             27.980605    27.980605
38             31.558509    29.458721
39             27.867751    23.221556
40             14.748934    14.748934
41             13.799727    14.367801
42             25.213954    26.471555
43             24.322523    24.322523
44             24.812133    33.620305
45             26.585110    29.405630
46              9.320976    11.450154
47             16.740829    16.925573
48             17.692417    16.667301
49             16.343508    18.443296
50             19.979771    57.659877
51             18.711186    16.582008
52             22.242170    22.057426
53             22.305753    21.799154
54             14.134634    23.575149
55              0.145917    -0.422156

In [55]:
import sklearn.metrics as metrics

# Calculate MAE, MSE, RMSE
print(metrics.mean_absolute_error(df5['Mean of correct edit'],pred))
print(metrics.mean_squared_error(df5['Mean of correct edit'], pred))
print(np.sqrt(metrics.mean_squared_error(df5['Mean of correct edit'], pred)))

6.958414076681819
81.27122853076811
9.015055658772614

## Algorithms for Ordinal Vectors

In [0]:
# Read HBB and HEXA file
df6 = pd.read_excel("ordinal.xlsx")

In [0]:
df6 = df6.drop(['Unnamed: 0'], axis=1)

In [0]:
# Features
X = df6.drop('Mean of correct edit', axis=1)

In [0]:
# Target variable
y = df6['Mean of correct edit']

In [0]:
# Splitting the dataset into the Training and Test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

## Multiple Linear Regression Model

In [67]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
# Use the regressor's predict method on the test data
pred= regressor.predict(X)

In [0]:
# Place predictions in the dataframe
df6['Predictions'] = pd.DataFrame(data=pred)

In [0]:
results = df6[['Mean of correct edit', 'Predictions']]

In [71]:
# Print the actual values and the model's predictions
results

    Mean of correct edit  Predictions
0              40.982414    16.156656
1              32.843033    34.258183
2              36.210669    35.273682
3              46.204905    45.551852
4              42.342045    41.863881
5              44.501013    41.931912
6              38.488102    46.220480
7              29.187135    28.948428
8              29.959730    29.963926
9              40.690499    40.242096
10             33.346109    36.554126
11             39.143062    36.622157
12             31.461293    31.793454
13              0.232247    -5.177021
14              0.243254    -2.054066
15              0.980358    -1.393953
16              3.285856     4.114968
17              4.693972    10.481921
18              7.288269     9.663267
19              7.889493    11.372090
20              0.343363     1.224888
21              0.221537     4.347843
22              2.560767     5.007956
23             13.011737    10.516877
24             19.012042    16.883830
25             19.868651    16.065176
26             22.122870    17.773999
27             22.895820    22.895820
28             15.632697    15.632697
29             12.021063    12.021063
30              9.072358    11.626727
31              7.162188    11.372090
32             11.391022    11.954590
33             11.071509     3.229859
34             32.697945    35.679663
35             24.046569    27.321325
36             32.673327    20.192963
37             27.980605    27.973797
38             31.558509    29.262089
39             27.867751    24.067886
40             14.748934    16.761048
41             13.799727    15.925655
42             25.213954    24.650386
43             24.322523    24.322523
44             24.812133    24.716859
45             26.585110    30.138772
46              9.320976    11.508192
47             16.740829    14.275050
48             17.692417    15.709547
49             16.343508    17.650311
50             19.979771     8.581185
51             18.711186    17.579078
52             22.242170    20.345936
53             22.305753    21.780433
54             14.134634    23.721197
55              0.145917    -1.980010

In [72]:
import sklearn.metrics as metrics

# Calculate MAE, MSE, RMSE
print(metrics.mean_absolute_error(df6['Mean of correct edit'],pred))
print(metrics.mean_squared_error(df6['Mean of correct edit'], pred))
print(np.sqrt(metrics.mean_squared_error(df6['Mean of correct edit'], pred)))

3.0556489544309033
25.249808033413533
5.024918709134859

# Support Vector Regression

In [0]:
# Use the regressor's predict method on the test data
SupportVectorRegModel = SVR()

In [74]:
SupportVectorRegModel.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
# Use the regressor's predict method on the test data
pred= SupportVectorRegModel.predict(X)

In [0]:
# Place predictions in the dataframe
df6['Predictions2'] = pd.DataFrame(data=pred)

In [0]:
results = df6[['Mean of correct edit', 'Predictions']]

In [78]:
# Print the actual values and the model's predictions
results

    Mean of correct edit  Predictions
0              40.982414    16.156656
1              32.843033    34.258183
2              36.210669    35.273682
3              46.204905    45.551852
4              42.342045    41.863881
5              44.501013    41.931912
6              38.488102    46.220480
7              29.187135    28.948428
8              29.959730    29.963926
9              40.690499    40.242096
10             33.346109    36.554126
11             39.143062    36.622157
12             31.461293    31.793454
13              0.232247    -5.177021
14              0.243254    -2.054066
15              0.980358    -1.393953
16              3.285856     4.114968
17              4.693972    10.481921
18              7.288269     9.663267
19              7.889493    11.372090
20              0.343363     1.224888
21              0.221537     4.347843
22              2.560767     5.007956
23             13.011737    10.516877
24             19.012042    16.883830
25             19.868651    16.065176
26             22.122870    17.773999
27             22.895820    22.895820
28             15.632697    15.632697
29             12.021063    12.021063
30              9.072358    11.626727
31              7.162188    11.372090
32             11.391022    11.954590
33             11.071509     3.229859
34             32.697945    35.679663
35             24.046569    27.321325
36             32.673327    20.192963
37             27.980605    27.973797
38             31.558509    29.262089
39             27.867751    24.067886
40             14.748934    16.761048
41             13.799727    15.925655
42             25.213954    24.650386
43             24.322523    24.322523
44             24.812133    24.716859
45             26.585110    30.138772
46              9.320976    11.508192
47             16.740829    14.275050
48             17.692417    15.709547
49             16.343508    17.650311
50             19.979771     8.581185
51             18.711186    17.579078
52             22.242170    20.345936
53             22.305753    21.780433
54             14.134634    23.721197
55              0.145917    -1.980010

In [79]:
import sklearn.metrics as metrics

# Calculate MAE, MSE, RMSE
print(metrics.mean_absolute_error(df6['Mean of correct edit'],pred))
print(metrics.mean_squared_error(df6['Mean of correct edit'], pred))
print(np.sqrt(metrics.mean_squared_error(df6['Mean of correct edit'], pred)))

10.77534987241704
167.6173344293209
12.946711336448375

## Algortihms for k-mers (k=3)

In [0]:
# Read HBB and HEXA file
df7 = pd.read_excel('kmers.xlsx')

In [0]:
df7 = df7.drop(['Unnamed: 0','pegRNA', '3extension'], axis=1)

In [0]:
# Features
X = df7.drop('Mean of correct edit', axis=1)

In [0]:
# Target variable
y = df7['Mean of correct edit']

In [0]:
# Splitting the dataset into the Training and Test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

## Multiple Linear Regression Model

In [100]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
# Use the regressor's predict method on the test data
pred= regressor.predict(X)

In [0]:
# Place predictions in the dataframe
df7['Predictions'] = pd.DataFrame(data=pred)

In [0]:
results = df7[['Mean of correct edit', 'Predictions']]

In [104]:
# Print the actual values and the model's predictions
results

    Mean of correct edit  Predictions
0              40.982414    40.468490
1              32.843033    34.178042
2              36.210669    36.210669
3              46.204905    47.016416
4              42.342045    41.007035
5              44.501013    45.468979
6              38.488102    44.882812
7              29.187135    27.852126
8              29.959730    29.884752
9              40.690499    40.690499
10             33.346109    34.681119
11             39.143062    39.143062
12             31.461293    39.012803
13              0.232247    -8.665161
14              0.243254    -4.271866
15              0.980358    -2.733700
16              3.285856     5.856768
17              4.693972     8.028281
18              7.288269     9.208612
19              7.889493    10.781535
20              0.343363     0.343363
21              0.221537     4.736658
22              2.560767     6.274824
23             13.011737    14.865292
24             19.012042    17.036805
25             19.868651    18.217137
26             22.122870    19.790059
27             22.895820    22.895820
28             15.632697    15.528142
29             12.021063    12.289893
30              9.072358    10.677024
31              7.162188    10.781535
32             11.391022    11.345323
33             11.071509    -0.114601
34             32.697945    29.236688
35             24.046569    22.793260
36             32.673327    24.331426
37             27.980605    28.249434
38             31.558509    26.087006
39             27.867751    24.695863
40             14.748934    10.324468
41             13.799727    13.799727
42             25.213954    25.259652
43             24.322523    24.591353
44             24.812133    26.204221
45             26.585110    29.442470
46              9.320976    12.495981
47             16.740829    15.249234
48             17.692417    18.252436
49             16.343508    21.546181
50             19.979771    19.790602
51             18.711186    17.242588
52             22.242170    19.995842
53             22.305753    22.999043
54             14.134634    26.292789
55              0.145917     0.145917

In [105]:
import sklearn.metrics as metrics

# Calculate MAE, MSE, RMSE
print(metrics.mean_absolute_error(df7['Mean of correct edit'],pred))
print(metrics.mean_squared_error(df7['Mean of correct edit'], pred))
print(np.sqrt(metrics.mean_squared_error(df7['Mean of correct edit'], pred)))

2.5091480420172187
14.0857105280476
3.753093461139437

# Support Vector Regression

In [0]:
# Use the regressor's predict method on the test data
SupportVectorRegModel = SVR()

In [107]:
SupportVectorRegModel.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
# Use the regressor's predict method on the test data
pred= SupportVectorRegModel.predict(X)

In [0]:
# Place predictions in the dataframe
df7['Predictions2'] = pd.DataFrame(data=pred)

In [0]:
results = df7[['Mean of correct edit', 'Predictions']]

In [111]:
# Print the actual values and the model's predictions
results

    Mean of correct edit  Predictions
0              40.982414    40.468490
1              32.843033    34.178042
2              36.210669    36.210669
3              46.204905    47.016416
4              42.342045    41.007035
5              44.501013    45.468979
6              38.488102    44.882812
7              29.187135    27.852126
8              29.959730    29.884752
9              40.690499    40.690499
10             33.346109    34.681119
11             39.143062    39.143062
12             31.461293    39.012803
13              0.232247    -8.665161
14              0.243254    -4.271866
15              0.980358    -2.733700
16              3.285856     5.856768
17              4.693972     8.028281
18              7.288269     9.208612
19              7.889493    10.781535
20              0.343363     0.343363
21              0.221537     4.736658
22              2.560767     6.274824
23             13.011737    14.865292
24             19.012042    17.036805
25             19.868651    18.217137
26             22.122870    19.790059
27             22.895820    22.895820
28             15.632697    15.528142
29             12.021063    12.289893
30              9.072358    10.677024
31              7.162188    10.781535
32             11.391022    11.345323
33             11.071509    -0.114601
34             32.697945    29.236688
35             24.046569    22.793260
36             32.673327    24.331426
37             27.980605    28.249434
38             31.558509    26.087006
39             27.867751    24.695863
40             14.748934    10.324468
41             13.799727    13.799727
42             25.213954    25.259652
43             24.322523    24.591353
44             24.812133    26.204221
45             26.585110    29.442470
46              9.320976    12.495981
47             16.740829    15.249234
48             17.692417    18.252436
49             16.343508    21.546181
50             19.979771    19.790602
51             18.711186    17.242588
52             22.242170    19.995842
53             22.305753    22.999043
54             14.134634    26.292789
55              0.145917     0.145917

In [112]:
import sklearn.metrics as metrics

# Calculate MAE, MSE, RMSE
print(metrics.mean_absolute_error(df7['Mean of correct edit'],pred))
print(metrics.mean_squared_error(df7['Mean of correct edit'], pred))
print(np.sqrt(metrics.mean_squared_error(df7['Mean of correct edit'], pred)))

10.430284437641834
155.4385810973711
12.467500996485667